[package]
name = "quake"
version = "0.1.0"
edition = "2018"
authors = ["Phodal HUANG <h@phodal.com>"]
description = """
Simple knowledge management tool for geek.
"""
documentation = "https://github.com/phodal/quake"
repository = "https://github.com/phodal/quake"
readme = "README.md"
license = "MIT"
exclude = ["_fixtures/*"]
autoexamples = true
keywords = ["knowledge", "dashboard"]

[dependencies]
clap = "3.0.0-beta.5"

config = { version = "0.11", features = ["yaml"] }

quake_core = { path = "quake_core", version = "0.1.0" }

regex = "1.0"
lazy_static = "1.4.0"

csv = "1.1"

walkdir = "2"

serde_yaml = "0.8"
serde = "1.0"
serde_derive = "1.0"

[workspace]
members = [
    'quake_core',
    'quake_gui',
    'quake_tui',
    'quake_database',
    'quake_importer',
]