[package]
name = "quake_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quake_core = { path = "../quake_core", version = "0.2.0" }
wasm-bindgen = "0.2"


[lib]
crate-type = ["cdylib"]
