name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          git fetch --tags
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: install libgtk-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libxkbcommon-dev libxkbcommon-x11-dev
        if: contains(matrix.os, 'ubuntu')

      # url: https://github.com/linebender/druid/blob/master/.github/workflows/ci.yml
      - name: install libx11-dev
        run: |
          sudo apt update
          sudo apt install libx11-dev libpango1.0-dev libxkbcommon-dev libxkbcommon-x11-dev
        if: contains(matrix.os, 'ubuntu')

      - name: install dioxus dependencies
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.0-dev libayatana-appindicator3-dev
        if: contains(matrix.os, 'ubuntu')

      - name: Run unit tests
        run: ${{matrix.ENV_VARS}} cargo test --all
