# from: https://github.com/clap-rs/clap/blob/master/.github/workflows/coverage.yml
name: Coverage
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    name: Coverage
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          override: true

      - name: Checkout
        uses: actions/checkout@v2


      - name: install libgtk-dev
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libxkbcommon-dev libxkbcommon-x11-dev
        if: contains(matrix.os, 'ubuntu')

      # url: https://github.com/linebender/druid/blob/master/.github/workflows/ci.yml
      - name: install libx11-dev
        run: |
          sudo apt update
          sudo apt install libx11-dev libpango1.0-dev libxkbcommon-dev libxkbcommon-x11-dev
        if: contains(matrix.os, 'ubuntu')

      # from: https://github.com/diesel-rs/diesel/blob/master/.github/workflows/ci.yml
      - name: Install sqlite (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          choco install sqlite
          cd /D C:\ProgramData\chocolatey\lib\SQLite\tools
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          lib /machine:x64 /def:sqlite3.def /out:sqlite3.lib

      - name: Set variables for sqlite (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_PATH
          echo "SQLITE3_LIB_DIR=C:\ProgramData\chocolatey\lib\SQLite\tools" >> $GITHUB_ENV
          echo "SQLITE_DATABASE_URL=C:\test.db" >> $GITHUB_ENV

      - name: Install llvm-cov
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-llvm-cov
          version: 0.1.0-alpha.4
          use-tool-cache: true

      - name: Coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --features "wrap_help yaml regex unstable-replace unstable-multicall unstable-grouped" --lcov --output-path lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.github_token }}
