name: Lint
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev


      - name: Cache Builds
        uses: Swatinem/rust-cache@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Clippy for all features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Clippy for tests
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests

      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
